[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [".git/", "cliff.toml"]

[default]
check-filename = true
extend-ignore-re = ["digest to \\b[0-9a-f]{7,}\\b"]

[default.extend-words]
# rattatui crate name
ratatui = "ratatui"
