[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [".git/"]

[default]
check-filename = true

[default.extend-words]
# rattatui crate name
ratatui = "ratatui"
# intentionally misspelled words in cliff.toml postprocessors
Simlify = "Simlify"
hanlding = "hanlding"
verision = "verision"
compileable = "compileable"
thouroughly = "thouroughly"
