Output demo.webm
Set Padding 0
Set FontSize 14
Set Width 1000
Set Height 600
Set Shell zsh
Set Theme "Catppuccin Mocha"
Set TypingSpeed 0.1
Type "mdns-tui-browser"
Enter
Sleep 2.5s
Right 7
Left 7
Sleep 2.5s
Type "o"
Sleep 2s
Type "o"
Sleep 2s
Type "s"
Sleep 2s
Type "s"
Sleep 2s
Type "s"
Sleep 1s
Type "/"
Type "denon"
Enter
Sleep 4s
Type "n"
Sleep 1s
Type "?"
Sleep 1s
Down
Down
Down
Down
Down
Sleep 2s
Type "q"
Type "m"
Sleep 1s
Down
Down
Down
Sleep 3s
Type "q"
Sleep 500ms
Type "q"
Sleep 1s
Ctrl+D
