# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Arch linux AUR

on:
  workflow_call:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  release-info:
    permissions:
      packages: read
    runs-on: ubuntu-slim
    outputs:
      version: ${{ steps.version.outputs.version }}
      tagName: ${{ steps.version.outputs.tagName }}
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: 🏷️ Get version info
        id: version
        uses: ./.github/actions/latest-release-info

  update-aur:
    needs:
      - release-info
    permissions:
      packages: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/mdns-browser-arch-aur-builder:v1@sha256:be72b19ab04414eac9720badac1a5127fffb87a6458791fa68ebe6758f98c272
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: mdns-tui-browser
            checksum_url: "https://github.com/hrzlgnm/mdns-tui-browser/releases/download/${{ needs.release-info.outputs.tagName }}/${{ needs.release-info.outputs.version }}.tar.gz.sha256"
            generate_script: "./packaging/aur/generate-mdns-tui-browser.sh"
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: 🔢 Get sha256sums
        id: sha256sums
        env:
          CHECKSUM_URL: ${{ matrix.package.checksum_url }}
        shell: bash
        run: |
          URL="$CHECKSUM_URL"
          echo "getting $URL"
          SUM=$(curl -LfsS "$URL" | cut -f1 -d ' ')
          echo "sha256=$SUM" >> "$GITHUB_OUTPUT"

      - name: 📐 Lint generated PKGBUILD
        env:
          VERSION: ${{ needs.release-info.outputs.version }}
          SHA256: ${{ steps.sha256sums.outputs.sha256 }}
          GENERATE_SCRIPT: ${{ matrix.package.generate_script }}
        shell: bash
        run: |
          su runner -c "
            set -o errexit
            mkdir -p ~/lint
            o=\$(pwd)
            \"\$GENERATE_SCRIPT\" \"\$VERSION\" \"\$SHA256\" > ~/lint/PKGBUILD
            cd ~/lint
            cat PKGBUILD
            \"\$o/packaging/aur/makepkg-lint.sh\"
          "

      - name: 🛠️ Setup Deployment keys
        if: github.event.release.tag_name
        shell: bash
        env:
          AUR_DEPLOY_KEY: ${{ secrets.AUR_DEPLOY_KEY }}
        run: |
          chown -R runner:runner .
          su runner -c "
            set -o errexit
            mkdir -p ~/.ssh
            printf '%s\n' \"\$AUR_DEPLOY_KEY\" > ~/.ssh/aur
            chmod 600 ~/.ssh/aur
            echo \"Host aur.archlinux.org\" >> ~/.ssh/config
            echo \"  IdentityFile ~/.ssh/aur\" >> ~/.ssh/config
            echo \"  User aur\" >> ~/.ssh/config
            ssh-keyscan -H aur.archlinux.org >> ~/.ssh/known_hosts
          "

      - name: 🔄 Clone AUR Repo
        if: github.event.release.tag_name
        shell: bash
        run: |
          su runner -c "
            set -o errexit
            git clone --depth=1 \"ssh://aur@aur.archlinux.org/${{ matrix.package.name }}.git\" ~/aur
          "

      - name: 🔍 Check version
        if: github.event.release.tag_name
        env:
          RELEASE_VERSION: ${{ needs.release-info.outputs.version }}
        shell: bash
        run: |
          su runner -c "
            set -o errexit
            cd ~/aur
            if [[ -f PKGBUILD ]]; then
              CURRENT_VERSION=\$(source PKGBUILD && echo \$pkgver)
              if [[ \"\$(printf \"%s\n%s\" \"\$CURRENT_VERSION\" \"\$RELEASE_VERSION\" | sort -V | head -n1)\" != \"\$CURRENT_VERSION\" ]] || [[ \"\$CURRENT_VERSION\" == \"\$RELEASE_VERSION\" ]]; then
                echo \"New version (\$RELEASE_VERSION) is not higher than the current version (\$CURRENT_VERSION). Exiting.\"
                exit 1
              fi
            fi
          "

      - name: 🌀 Generate PKGBUILD update and publish
        if: github.event.release.tag_name
        env:
          VERSION: ${{ needs.release-info.outputs.version }}
          SHA256: ${{ steps.sha256sums.outputs.sha256 }}
          GENERATE_SCRIPT: ${{ matrix.package.generate_script }}
        run: |
          su runner -c "
            set -o errexit
            \"\$GENERATE_SCRIPT\" \"\$VERSION\" \"\$SHA256\" > ~/aur/PKGBUILD
            cd ~/aur
            if [[ -z \$(git status --porcelain) ]]; then
              echo \"No changes\"
              exit 0
            fi
            makepkg --printsrcinfo > .SRCINFO
            makepkg
            makepkg --install --noconfirm
            git config user.name \"hrzlgnm\"
            git config user.email \"hrzlgnm@users.noreply.github.com\"
            git add PKGBUILD .SRCINFO
            git commit -m \"New upstream release \$VERSION\"
            git push origin master
          "
