# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "CI"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  # measure against bitrot
  # also rotates docker images monthly, by pushing new docker images
  # the rotation will happen by renovate
  # rotate the images in the middle of the month,
  # to avoid duplicate rotations at the beginning of the month,
  # as the source docker images are also mostly rotated once a month
  schedule:
    - cron: "0 0 15 * *"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

permissions:
  contents: read # Minimal default needed for change detection

concurrency:
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  label-pr:
    if: github.event_name == 'pull_request'
    name: "🏷️ Label PR"
    permissions:
      contents: read # Needed to read repository contents
      pull-requests: write # Needed to apply labels
      issues: write # Needed to create non existing labels
    runs-on: ubuntu-slim

    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          configuration-path: .github/labeler.yml

  changes:
    name: "🔍 Detect Changes"
    runs-on: ubuntu-slim
    outputs:
      aur: ${{ steps.filter.outputs.aur }}
      branch: ${{ steps.branch.outputs.branch }}
      code: ${{ steps.filter.outputs.code }}
      lint: ${{ steps.filter.outputs.lint }}
      tests: ${{ steps.filter.outputs.tests }}
      winget: ${{ steps.filter.outputs.winget }}
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 🔍 Check for changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            aur:
              - '.github/workflows/aur-reusable.yml'
              - '.github/actions/latest-release-info/action.yml'
              - 'packaging/aur/**'
              
            code:
              - '.github/actions/setup-*/**'
              - '.github/workflows/build-reusable.yml'
              - 'src/**'
              - 'src-tauri/Cargo.toml'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'Cross.toml'
            lint:
              - '.github/workflows/lint-reusable.yml'
            tests:
              - '.github/workflows/test-reusable.yml'
              - '.config/nextest.toml'
            winget:
              - '.github/workflows/winget-reusable.yml'
              - '.github/actions/latest-release-info/action.yml'
      - name: Output branch name
        id: branch
        run: |
          echo "branch=${{ env.BRANCH_NAME }}" >> "$GITHUB_OUTPUT"

  typos:
    name: 📝 Check typos
    if: always()
    uses: hrzlgnm/actions/.github/workflows/typos-reusable.yml@8984a8157c97612f08eb5363a6995e9497eee7fe # v2.5.5

  actionlint:
    if: always()
    uses: hrzlgnm/actions/.github/workflows/actionlint-reusable.yml@8984a8157c97612f08eb5363a6995e9497eee7fe # v2.5.5

  lint:
    permissions:
      contents: read
    needs:
      - changes
      - actionlint
    if: needs.changes.outputs.code == 'true' || needs.changes.outputs.lint == 'true'
    uses: ./.github/workflows/lint-reusable.yml

  tests:
    permissions:
      contents: read # Needed to checkout code for testing
      checks: write # Required for action-junit-report annotation
    needs:
      - changes
      - actionlint
    if: needs.changes.outputs.code == 'true' || needs.changes.outputs.tests == 'true'
    uses: ./.github/workflows/test-reusable.yml

  build:
    name: "build"
    needs:
      - changes
      - actionlint
    if: needs.changes.outputs.code == 'true'
    permissions:
      contents: read # Needed to run build and pass permissions to reusable workflow
    uses: ./.github/workflows/build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ needs.changes.outputs.branch }}

  aur:
    name: AUR
    needs:
      - changes
      - actionlint
    if: needs.changes.outputs.aur == 'true'
    permissions:
      contents: read # Needed to checkout code and run local scripts for AUR build
      packages: read # Needed to read container image for AUR build
    uses: ./.github/workflows/aur-reusable.yml

  winget:
    name: winget
    needs:
      - changes
      - actionlint
    if: needs.changes.outputs.winget == 'true'
    permissions:
      contents: read # Needed to download release assets for winget submission
    uses: ./.github/workflows/winget-reusable.yml
    secrets: inherit

  cache-tools:
    needs:
      - build
      - lint
      - tests
    name: "📦 Cache tools"
    if: always() && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
    permissions:
      contents: read # Needed to checkout code for caching tools
    uses: ./.github/workflows/cache-tools-reusable.yml

  all-required-green: # This job does nothing and is only used for the branch protection
    name: CI Status
    runs-on: ubuntu-latest
    needs:
      - actionlint
      - aur
      - build
      - lint
      - tests
      - typos
      - winget
      - cache-tools
    if: always()
    steps:
      - name: Check whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@a638d6464689bbb24c325bb3fe9404d63a913030
        with:
          allowed-skips: >-
            aur,
            lint,
            tests,
            build,
            winget,
            cache-tools,
          jobs: ${{ toJSON(needs) }}
